### ISSUE TITLE
naoqi 2.1.4 authentication error

### ISSUE THREAD

**Issue by ng2dev** [lugu/qiloop#19]
Hello,

I was wondering if this library supports v5 nao based on naoqi 2.1.4?
I am running this command and get the following error

      ➜  ~ qiloop --qi-url tcp://192.168.2.9:9559 info --service ALVideoDevice
      message dropped: no handler match: [Type: capability, ID: 2550, Service: 0, Object: 0, Action: 0, Size: 79]
       connect: contact server: contact service: service connection error (ServiceDirectory): service 
       connection error (ServiceDirectory): authentication error: authentication failed: call authenticate 
       failed: can't find service, address: {0.0.8, id:3}

the contents of $HOME/.qiloop-auth.conf exist as expected.
Would you know why this happens?

**Comment by lugu** [comment]
Hi ng2dev,

Apparently the authentication procedure has changed since version 2.1. Let me download Choregraph 2.1 to see what can be done. I will get back to you.

**Comment by lugu** [comment]
Closed the issue by mistake.

**Comment by ng2dev** [comment]
Thank you! Though it might be tricky to instal choreograph 2.1 on a current linux system because of the libpng and zlib dependency. Let me know if it works for you. Otherwise I can dig into your code/help debug by next week Tuesday. Besides thank you for your work on this library!

**Comment by lugu** [comment]
My usual trick is to only run the naoqi-bin binary from Choregraph. You will hear from me soon :)

**Comment by lugu** [comment]
@ng2dev : i would love to hear what you would like to do on NAO.  Please share with me your story so it can inspire me to improve qiloop !

**Comment by ng2dev** [comment]
Thank you alot - it works great now!
My story: I was part of the Aldebaran developer program in 2012 till it was acquired by Softbank and ever since then have an extremely close bond with my Nao.
Nowadays I use golang for my professional work and I have the chance to participate in the antler.co entrepreneurship program starting in January. I want to use my knowledge of Nao to facilitate in building out a great startup idea utilizing natural language interfaces and hopefully change the world.
Therefore, after some study of your code - I came to the conclusion that this library is quite brilliant. I would like to actively contribute to it and help you with development/ backtest on a v5 Nao.   
I will create some more PR's on my own over the coming months - but if you have something in mind you might like to collaborate on - please do let me know - I will help out!

**Comment by lugu** [comment]
Sorry for the late reply. Thanks a lot for sharing! I am excited to discover what this idea is about :) I wish you good luck for January! I have seen you have already send a PR : thanks !!
