### ISSUE TITLE
use opencv capabilities with go

### ISSUE THREAD

**Issue by ng2dev** [lugu/qiloop#26]
I found this interesting library ->

     https://github.com/Niraj-Fonseka/recognize

It deploys a python opencv2 grpc server called from a go client.
Should we add this example to qiloop?
What would be the best approach here as nao v5 already has opencv2 pre-installed as well as nao v6 coming with opencv3 from what I have read.

Alternatively, it would be possible to run opencv off Nao and just stream ALVideoDevice into an external opencv lib -> such is described here with a webcam capture example.

     https://medium.com/@fonseka.live/detect-faces-using-golang-and-opencv-fbe7a48db055
     https://gocv.io/

Would be interested in your opinion what might be the best way to marry qiloop and opencv or gocv capabilities.

Thanks for your time.

**Comment by lugu** [comment]
Please take a look at pigo:
https://github.com/esimov/pigo
It does face detection only.

For an example of how to use video device with qiloop, take a look at: 
https://github.com/lugu/qiview

**Comment by ng2dev** [comment]
Thank you will check it out and report back!

**Comment by lugu** [comment]
qiview has been updated to demonstrate how to do face detection with pigo.
see: https://github.com/lugu/qiview/blob/master/face/face.go
